Implement up- and downgrade ability, bump v0.2.0

diff --git a/dj b/dj
--- a/dj
+++ b/dj
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # ------------------------------------------------------------------
-# Copyleft (C) Ákos Kovács - 2016
+# Copyleft (C) Ákos Kovács - 2017
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
@@ -27,6 +27,8 @@ SH_RC_FILE=".bashrc"
 DJEXE="dj"
 JMP_FN="j"
 DJFILE="dj.list"
+REPO="https://raw.githubusercontent.com/akoskovacs/dirjumper/master"
+#REPO="http://localhost:8000"
 
 DJDIR=".dirjumper"
 
@@ -35,7 +37,7 @@ DJLIST="$DJPATH/$DJFILE"
 DJBIN="$DJPATH/bin"
 
 USAGE="Usage: $DJEXE -ardgihv args"
-VERSION="0.1.1"
+VERSION="0.2.0"
 
 COLOR_RED="\x1b[31m"
 COLOR_BLUE="\x1b[34m"
@@ -116,7 +118,7 @@ delete_alias () {
 }
 
 init_sh () {
-  echo "export PATH=\"\$PATH:$DJBIN\""
+  echo -e "alias dj=$0"
   echo -e "$JMP_FN () {\n\tif [[ \$1 = \"\" ]]; then\n\t\t$0 -l\n\telse"
   echo -e "\t\tcd \$($0 -g \$1)\n\tfi;\n}\n"
 }
@@ -135,25 +137,75 @@ install_dirjumper () {
   echo "And then use 'j <alias>' to return here."
 }
 
+update_dirjumper () {
+  echo -e "${COLOR_YELLOW}Checking for new version...${COLOR_END}"
+
+  cd $DJBIN
+  new_version=$(wget "$REPO/VERSION" -O- -o /tmp/dj.log)
+  if [ $? -ne 0 ]; then 
+      cat /tmp/dj.log
+      echo -e "${COLOR_RED}Error while downloading version information!${COLOR_END}"
+      exit 1
+  fi;
+  if [ $VERSION = $new_version ]; then
+      echo -e "${COLOR_GREEN}Your version is up-to-date (v$VERSION).${COLOR_END}"
+      exit 0
+  fi;
+  echo -ne "${COLOR_YELLOW}New version (v$new_version) found. Do you want to upgrade? [y/N]: ${COLOR_END}"
+  read answ
+  if [ $answ = "y" -o $answ = "Y" ]; then
+    mv dj dj.old
+    wget "$REPO/dj" -o/tmp/dj.log
+    if [ $? -ne 0 ]; then
+      cat /tmp/dj.log
+      echo -e "${COLOR_RED}Error while downloading upgrades!${COLOR_END}"
+      exit 1
+    fi;
+    chmod +x dj
+    echo -e "${COLOR_GREEN}Upgrade done...${COLOR_END}"
+    rm /tmp/dj.log
+  else
+      echo -e "${COLOR_RED}Upgrade aborted.${COLOR_END}"
+      exit 1
+  fi;
+  exit 0
+}
+
+downgrade_dirjumper () {
+  cd $DJBIN
+  if [ -e dj.old ]; then
+    old_version=$(./dj.old -v)
+    mv dj dj.older
+    mv dj.old dj
+    mv dj.older dj.old
+    echo -e "${COLOR_GREEN}Sucessfully downgraded from '${old_version}' to '${VERSION}'.${COLOR_END}"
+    exit 0
+  else
+    echo -e "${COLOR_RED}No older version found!${COLOR_END}"
+    exit 1
+  fi;
+}
+
 print_help () {
   echo $USAGE
-  echo
   echo -e "\t-a <ALIAS> <DIR>\t\tAdd an alias, use the working dir. if <DIR> is not set"
   echo -e "\t-r <OLD-ALIAS> <NEW-ALIAS>\tRename a directory alias"
   echo -e "\t-d <ALIAS>\t\t\tDelete a directory alias"
   echo -e "\t-g <ALIAS>\t\t\tGet the full path for an alias"
-  echo -e "\t-l\t\t\t\tList all aliases"
+  echo -e "\t-l\t\t\t\tList all aliases\n"
+  echo -e "\t-u\t\t\t\tUpgrade the script to the latest version"
+  echo -e "\t-w\t\t\t\tDowngrade the script to an older version\n"
   echo -e "\t-h\t\t\t\tThis help message"
   echo -e "\t-v\t\t\t\tThe version of the script"
   echo
   echo "To jump, use '$JMP_FN <alias>'."
 }
 
-while getopts "a:g:r:d:lisvh" optname
+while getopts "a:g:r:d:liuwsvh" optname
   do
     case "$optname" in
       "v")
-        echo "Version $VERSION"
+        echo $VERSION
         exit 0;
         ;;
       "a")
@@ -177,6 +229,12 @@ while getopts "a:g:r:d:lisvh" optname
         list_aliases
         exit 0;
         ;;
+      "u")
+        update_dirjumper
+        ;;
+      "w")
+        downgrade_dirjumper
+        ;;
       "g")
         get_alias $OPTARG
         exit 0;
@@ -186,21 +244,15 @@ while getopts "a:g:r:d:lisvh" optname
         exit 0;
         ;;
       "?")
-        echo -en $COLOR_RED
-        echo "Unknown option $OPTARG"
-        echo -en $COLOR_END
+        echo -e "${COLOR_RED}Unknown option $OPTARG${COLOR_END}"
         exit 0;
         ;;
       ":")
-        echo -en $COLOR_RED
-        echo "No argument value for option $OPTARG"
-        echo -en $COLOR_END
+        echo -e "${COLOR_RED}No argument value for option $OPTARG${COLOR_END}"
         exit 0;
         ;;
       *)
-        echo -en $COLOR_RED
-        echo "Unknown error while processing options"
-        echo -en $COLOR_END
+        echo -e "${COLOR_RED}Unknown error while processing options${COLOR_RED}"
         exit 0;
         ;;
     esac
@@ -215,7 +267,6 @@ if [ ! -e $DJLIST ]; then
   chmod +x $DJBIN/$DJEXE
   $DJBIN/$DJEXE -i
   rm $DJEXE
-  echo "After creating a new bash instance you can use all commands."
 else
   if [[ $# == 0 ]]; then
     print_help
